---
title: "lab7"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(broom)
library(nnet)
library(broom)
library(pROC)
library(plotROC) 
library(arm)

```

Exercise 1: 

```{r}
data <- read.csv("data.csv")
glimpse(data)
```
```{r}

data_lv <- data %>% mutate(target = as.factor(target), key = as.factor(ifelse(key == 2, "D", ifelse(key == 3, "D#", "Other"))))

glimpse(data_lv)
```


```{r}
p <- ggplot(data = data_lv, aes(x = key, fill = target)) +
  geom_bar(position = "fill") +
  labs(y = "Proportion", 
       title = "target vs key") +
  coord_flip()
p
```
Exercise 2: 
```{r}
target_m_red <- glm(target ~ acousticness + danceability + duration_ms + instrumentalness + loudness + speechiness + valence, 
              data = data_lv, family = binomial)
tidy(target_m_red, conf.int = TRUE, exponentiate = FALSE) %>% 
  kable(format = "markdown", digits = 3)
```
Exercise 3: 
```{r}
target_m_full <- glm(target ~ acousticness + danceability + duration_ms + instrumentalness + loudness + speechiness + valence + key, 
              data = data_lv, family = binomial)
```

```{r}

anova(target_m_red, target_m_full, test = "Chisq")
```

There is evidence to suggest that the key is a significant predictor because we have a low p value of .001258. 


Exercise 4:

```{r}
model <- target_m_full 
tidy(model, conf.int = TRUE, exponentiate = FALSE) %>% 
  kable(format = "markdown", digits = 3)
```
The keyD# coefficent tells us how the log odds of the target = 1 will change if our track is in the key of D#. 

Exercise 5:

```{r}
m_aug <- augment(model, type.predict = "response", 
                      type.residuals = "deviance")


```
Exercise 6:
```{r}
arm::binnedplot(x = m_aug$.fitted, y = m_aug$.resid,
                xlab = "Predicted Probabilities", 
                main = "Binned Residual vs. Predicted Values", 
                col.int = FALSE)
```
Exercise 7:
```{r}
arm::binnedplot(x = m_aug$instrumentalness, 
                y = m_aug$.resid, 
                col.int = FALSE,
                xlab = "instrumentalness", 
                main = "Binned Residual vs. instrumentalness")
```
Exercise 8: 
```{r}
m_aug %>%
  group_by(key) %>%
  summarise(mean_resid = mean(.resid))
```

Exercise 9: 
TO DO

Exercise 10:
```{r}
(roc_curve <- ggplot(m_aug, 
                     aes(d = as.numeric(target) - 1, 
                         m = .fitted)) +
  geom_roc(n.cuts = 5, labelround = 3) + 
  geom_abline(intercept = 0) + 
  labs(x = "False Positive Rate (1 - Specificity)", 
       y = "True Positive Rate (Sensitivity)") )
calc_auc(roc_curve)$AUC

```
Exercise 11:
TODO

Exercise 12:
```{r}
threshold <- .493
```
TODO 

Exercise 13:

```{r}
m_aug %>%
  mutate(predict_target = if_else(.fitted > threshold, "1", "0")) %>%
  group_by(target, predict_target) %>%
  summarise(n = n()) %>%
  kable(format="markdown")
```
Exercise 14:
TODO




